### PR TITLE
Adding a few good intro to Clojure books

### PR DESCRIPTION
**Pull request by arkdrag**

### CODE REVIEW

**Comment by puredanger** [comment]
There's actually an existing list of these that needs to be moved here if you wanted to steal the whole list:

https://github.com/clojure/clojure-site/blob/master/content/guides/getting_started.adoc#books

**Comment by puredanger** [comment]
Looks like you added everything here. Can we add just the books from Getting Started to the books page? And remove them from the Getting Started page?

**Comment by htmfilho** [comment]
Do you guys need some help here?

**Comment by puredanger** [comment]
I took the other PR for this instead as it was a bit prettier - thanks though!

**Pull request closed without merging**
