### PR TITLE
Add The REPL - a Clojure newsletter to community resources

### PR DESCRIPTION
**Pull request by danielcompton**

### CODE REVIEW

**Comment by puredanger** [comment]
Can you undo the date change? That's a creation date, so doesn't need to change.

**Comment by puredanger** [comment]
whoops didn't mean to close it!

**Comment by puredanger** [comment]
I've updated the newsletters section to add the REPL in the next deploy, so closing this PR.

**Comment by danielcompton** [comment]
Sorry, I read your comment on my phone and forgot to come back to it. Thanks!

**Pull request closed without merging**
