### PR TITLE
java_interop: how to attach java annotations

### PR DESCRIPTION
**Pull request by holyjak**
- [x] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [x] Have you signed the Clojure Contributor Agreement?
- [x] Have you verified your asciidoc markup is correct?

### CODE REVIEW

**Comment by puredanger** [comment]
There is an example of annotations at https://clojure.org/reference/datatypes#_java_annotation_support. Would prefer to add a pointer there from java_interop (and maybe compilation) pages. Definitely don't want to just point into the middle of a test, so that's a no go.

**Comment by holyjak** [comment]
Thank you for the pointer! Fixed.

**Comment by holyjak** [comment]
@puredanger Is the PR OK now? Thank you!

**Comment by puredanger** [comment]
the links  here should be xrefs...

`<<metadata#,metadata>` and `<<datatypes#_java_annotation_support,datatypes reference>>`

**Comment by holyjak** [comment]
Thank you, @puredanger ! I am sorry I haven't managed to fix the links in time.

**Pull request merged**
