### PR TITLE
Patch 1 - updated book list

### PR DESCRIPTION
**Pull request by juliangamble**
Added books to book page. 

Please support these fine books about Clojure.

### CODE REVIEW

**Comment by htmfilho** [comment]
The links to the books seems to be associated with an Amazon Associate account. I suggest changing the links to direct ones.

**Comment by juliangamble** [comment]
Perhaps I'm mistaken - but are you referring to the URLs image thumbnails? I think you'll find that the thumbnails on the existing page http://clojure.org/books follow this format. I was just trying to be consistent. Could you give an example of what you mean?

**Comment by htmfilho** [comment]
My mistake. I thought it was the links pointing to the books. Sorry for that.

**Comment by puredanger** [comment]
fyi, Rich has used affiliate links for books on this page in the past, but I will take care of those modifications.

**Pull request merged**
