### PR TITLE
Update hashed_colls.adoc

### PR DESCRIPTION
**Pull request by mikkolukas**
Corrected an oversight in "Sal" -> "Fred", for consistency.

- [x] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [x] Have you signed the Clojure Contributor Agreement?
- [x] Have you verified your asciidoc markup is correct?

### CODE REVIEW

**Comment by puredanger** [comment]
The example is fine as is, can you explain? Note that players is `#{"Alice", "Bob", "Kelly"}` - the example is showing that it's fine to disj both elements in the set and elements not in the set (no op).

**Comment by mikkolukas** [comment]
Thanks for your kind reply.

Oh, but you are right. As you mention it, I see that I misread the example as if we were removing from #{"Alice" "Fred" "Bob" "Kelly"}, but of course we are not, as players are defined as #{"Alice", "Bob", "Kelly"}

My mistake. I'm still new to Clojure and still learning (hence the beginners guide :) )

Again, thanks for the kind tone :)

**Comment by puredanger** [comment]
If some more words to clarify would help here, that would be a good update.

**Comment by mikkolukas** [comment]
Then it should be adding something along your phrase "it's fine to disj both elements in the set and elements not in the set".
It is not necessary, as my pull request was more due to too fast reading instead of a poor example.

It can be added as a nice-to-have, if you think it can help others, new to Clojure :)

**Pull request closed without merging**
