### PR TITLE
Installation in one command

### PR DESCRIPTION
**Pull request by audriu**
Making installation a little bit easier for new people to come and be more encouraged.

- [x] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [x] Have you signed the Clojure Contributor Agreement?
- [x] Have you verified your asciidoc markup is correct?

### CODE REVIEW

**Comment by audriu** [comment]
Also - I think that installer could use something like https://sdkman.io/install and install only in home dir. so people could use this installer in environments without sudo. What you think about it?

**Comment by SevereOverfl0w** [comment]
I'd prefer this wasn't recommended due to the many problems with piping directly into bash.

https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/
https://www.seancassidy.me/dont-pipe-to-your-shell.html

**Comment by audriu** [comment]
> I'd prefer this wasn't recommended due to the many problems with piping directly into bash.
> 
> https://www.idontplaydarts.com/2016/04/detecting-curl-pipe-bash-server-side/
> https://www.seancassidy.me/dont-pipe-to-your-shell.html

but both of these assume malicious server. Which Clojure-site is not. One on sites even uses words like "stupid" and "dumb" - how professional...

**Comment by puredanger** [comment]
Assuming you haven't been MITM'ed and you're actually talking to the server....

**Comment by audriu** [comment]
@puredanger please close it if you see no purpose...

**Comment by audriu** [comment]
IMHO if you have MITM - you are already hacked...

**Comment by SevereOverfl0w** [comment]
The Sean Cassidy article actually mentions other issues with piping, those related to having an unstable WiFi connection.

**Pull request closed without merging**
