### PR TITLE
Update deps_and_cli.adoc

### PR DESCRIPTION
**Pull request by Crowbrammer**
Disambiguate the Deps and CLI guide from the reference.

- [X] Have you read the [guidelines for contributing](https://clojure.org/community/contributing_site)?
- [X] Have you signed the Clojure Contributor Agreement?
- [X] Have you verified your asciidoc markup is correct?

### CODE REVIEW

**Comment by puredanger** [comment]
I don’t think this is needed - the reference is already mentioned and linked at the end of the intro

**Comment by Crowbrammer** [comment]
There are two pull requests, one for the guide, and one for the reference.

The guide has the link at the end of the intro. The reference does not. 

The fact that you're confusing these two proves that disambiguation is needed.

**Comment by puredanger** [comment]
Sorry, this comment was on the wrong PR (was reviewing from my phone). I've added a list of relevant links to the reference intro.

**Comment by Crowbrammer** [comment]
That works! Thank you!

**Pull request closed without merging**
