### PR TITLE
Add docs for setting compiler settings in Leiningen

### PR DESCRIPTION
**Pull request by danielcompton**
I took a look at the boot docs and wasn't sure how to set the JVM opts for the running application. Possibly @micha might be able to provide guidance on this for Boot?

### CODE REVIEW

**Comment by micha** [comment]
Since Boot runs in a single JVM you can't specify JVM options in your Clojure code, you need to use the `BOOT_JVM_OPTIONS` environment variable (or set it in your `boot.properties` file).

See: https://github.com/boot-clj/boot/wiki/JVM-Options

**Comment by puredanger** [comment]
We would prefer not to put tool-specific things in the reference docs. Would rather see this someplace else.

**Comment by danielcompton** [comment]
Would you like this to be in a guide instead? There's not a lot to say here which is why I put it in the reference material, but I can create a guide instead.

I understand that you'd prefer not to put tool specific things in the reference docs, but it isolates Clojure from the tooling that surrounds it, and the community that uses the tooling. The same thing can be seen on http://clojure.org/guides/getting_started. While you *can* create a REPL from bare Java, I don't think it's a particularly useful starting point for a newbie, nor is it what 99+% of the Clojure community uses for their REPL.

**Comment by neganp** [comment]
Isolation is a good thing! The language  and compiler are separate-from-but-related-to the tools that drive them, so lets keep the documentation separate but linked. We don't want to have to update the docs in two years when some awesome educational environment comes out and we send all our beginners there.

I'd agree with "put it in a guide".

**Comment by arrdem** [comment]
Maybe an appropriate compromise is to mention how to set JVM options in the respective tools' getting started guides and then to provide footnotes here in the official guide docs mentioning the respective directions for setting JVM options.

I propose that this is a way to moderate between reaching users where they actually are in terms of relying on other tools such as leiningen and boot without implying that either are somehow cannon.

**Comment by danielcompton** [comment]
[This is a good example](http://stackoverflow.com/questions/34926360/how-start-socket-repl-in-clojure-1-8-from-lein-or-boot) of the type of confusion that people have after reading the reference docs and trying to apply it to their own tooling. I'm not saying that the reference docs need to have the tool specific docs, but there should be docs somewhere.

**Comment by danielcompton** [comment]
I've updated the docs to point to Leiningen and Boot's documentation on setting environment variables. Hold off on merging it, as I'm still waiting on https://github.com/technomancy/leiningen/pull/2070, and the final URL may change.

**Comment by danielcompton** [comment]
This has been merged into Leiningen now.

**Comment by danielcompton** [comment]
@puredanger are the changes pointing to Lein and Boot docs for JVM opts ok?

**Comment by puredanger** [comment]
I haven't looked at it yet - I will do so the next time I allocate a timeslice. :)

**Comment by danielcompton** [comment]
@puredanger have you had a chance to look at this yet?

**Comment by puredanger** [comment]
I don't want to add these links to the reference page as there will be no end of things that could possibly be linked. Would rather have guides that cover tool configuration.

**Pull request closed without merging**
