### PR TITLE
Keeping contributor's fork up-to-date

### PR DESCRIPTION
**Pull request by htmfilho**
Added instructions to update the fork before working on a large change.

### CODE REVIEW

**Comment by danielcompton** [comment]
Should this be using `rebase` or `reset`? I don't think you're going to want people's merge commits if they happen to have done something on their local master accidentally.

**Comment by arrdem** [comment]
@danielcompton yeah this should be `git reset --hard upstream/master`. Some commentary about branch hygene and not working on master so that this doesn't bite you may be required, but as-is this will generate merge commits containing unmerged patches.

**Comment by htmfilho** [comment]
What do you guys think of this new version?

> 2. Add this repository to your remote urls: `git remote add upstream https://github.com/clojure/clojure-site.git`.
> 1. Before every contribution:
   - fetch the content of upstream: `git fetch upstream` ;
   - move to your master branch: `git checkout master` (in case you aren't already there); 
   - clean your master branch of any umplanned modifications by reseting the HEAD to the fetched branch: `git reset --hard upstream/master`; and
   - create a new branch as explained above: `git checkout -b <branchname>`

**Comment by danielcompton** [comment]
Looks good to me.

**Comment by puredanger** [comment]
There's a typo in there - "umplanned". Otherwise, sounds good to me.

**Pull request merged**
